### ISSUE TITLE
Fixed?

### ISSUE THREAD

**Issue by frasermarch** [JamesIde/clerk-next13-app-dir-woes#2]
Did you figure out what was wrong here?

**Comment by frasermarch** [comment]
sorry just seen the pr to fix

**Comment by JamesIde** [comment]
Thanks @frasermarch, yeah James helped out. Think it was the placement of the middleware.ts file which is different across pages/app dir + clerk so it was a bit confusing!

**Comment by frasermarch** [comment]
I've got my middleware in /src, and it's definitely being called, but I'm still getting this error

**Comment by JamesIde** [comment]
@frasermarch I've parked all dev work with nextjs/clerk. Maybe try clone the repo after James PRd in changes and see if that helps. Other than that, the Clerk discord is a good place to ask for help https://discord.com/invite/b5rXHjAg7A
